### ISSUE TITLE
What function is being returned by r.http that you are calling here?

### ISSUE THREAD

**Issue by theconektd** [rethinkdb/earthquake-map#3]
In this spot you are calling r.http and it seems to be returning a function which you are calling with "features".
https://github.com/rethinkdb/earthquake-map/blob/master/app.js#L18

I've looked through the docs and I can't find any reference to this style. What are you doing there and is there something in the docs somewhere?

Thanks. :)

**Comment by dalanmiller** [comment]
`r.http` is a HTTP client built into RethinkDB that can be used to make HTTP requests. In this example, `r.http` is making a GET request to USGS to return earthquake data in JSON format. Since we know that `features` is one of the properties/fields at the topmost level of the document we can automatically pluck that field (and it's object value) to return. 

It's the same as if we had the entire JSON as a Javascript Object already and called `json_object['features']` or `json_object.features`. 

[`.merge()` allows you to bring together two documents](http://rethinkdb.com/api/javascript/merge/) or create new fields from fields that existed in the original document (or both I suppose). For convenience the longitude and latitude are being merged into a single field and made into a [geometry object of type Point](http://rethinkdb.com/api/javascript/point/).  

If this is still confusing, I'd suggest breaking it down in the data explorer shown here:

![screenshot 2015-07-15 16 42 50](https://cloud.githubusercontent.com/assets/863286/8712388/97835068-2b10-11e5-8cea-6af2b8db547f.png)

**Comment by theconektd** [comment]
Thanks, but that's not what I was asking. I understand what the code is doing.
What I don't understand is what function he was passing "features" to.

I actually just found what I was looking for in the docs here:
http://rethinkdb.com/api/javascript/bracket/
